[options]

girs_directories = ["girs"]

library = "Atspi"
version = "2.0"
min_cfg_version = "2.38"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
generate = [
"Atspi.ControllerEventMask",
"Atspi.DeviceEventMask",
"Atspi.KeyEventMask",
"Atspi.KeystrokeListener",
"Atspi.Action",
"Atspi.Collection",
"Atspi.Component",
"Atspi.Document",
"Atspi.EditableText",
"Atspi.Hypertext",
"Atspi.Image",
"Atspi.Selection",
"Atspi.Table",
"Atspi.TableCell",
"Atspi.Text",
"Atspi.Value",
"Atspi.Hyperlink",
"Atspi.Relation",
"Atspi.Role",
"Atspi.StateSet",
"Atspi.Cache",
"Atspi.Object",
"Atspi.Application",
"Atspi.MatchRule",
"Atspi.CollectionSortOrder",
"Atspi.CollectionTreeTraversalType",
"Atspi.CollectionMatchType",
"Atspi.CoordType",
"Atspi.Rect",
"Atspi.ComponentLayer",
"Atspi.Point",
"Atspi.ScrollType",
"Atspi.Device",
"Atspi.KeyDefinition",
"Atspi.EventType",
"Atspi.DeviceEvent",
"Atspi.DeviceLegacy",
"Atspi.DeviceListener",
"Atspi.DeviceListenerCB",
"Atspi.DeviceListenerSimpleCB",
"Atspi.DeviceX11",
"Atspi.Event",
"Atspi.EventListener",
"Atspi.EventListenerCB",
"Atspi.EventListenerSimpleCB",
#"Atspi.EventListenerMode",
"Atspi.Range",
"Atspi.KeyEventType",
"Atspi.KeyListenerSyncType",
#"Atspi.KeySet",
"Atspi.KeySynthType",
"Atspi.LocaleType",
"Atspi.ModifierType",
"Atspi.RelationType",
"Atspi.StateType",
"Atspi.TextRange",
"Atspi.TextClipType",
"Atspi.TextGranularity",
"Atspi.TextBoundaryType",

]

manual = [
"GLib.DestroyNotify",
"GLib.Error",
"GLib.MainContext",
"DBus.Connection",
"GObject.Object",
"GObject.Value",
"GObject.ValueArray",
]
