[options]

girs_directories = ["girs"]

library = "Atspi"
version = "2.0"
min_cfg_version = "2.38"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
]