// Generated by gir (https://github.com/gtk-rs/gir @ f64f90a)
// from girs (@ 520ff74)
// DO NOT EDIT

#[allow(unused_imports)]
use crate::auto::*;

pub type ControllerEventMask = u32;
pub type DeviceEventMask = u32;
pub type KeyEventMask = u32;
pub type KeystrokeListener = /*Unimplemented*/();
