// Generated by gir (https://github.com/gtk-rs/gir @ f64f90a)
// from girs (@ 520ff74)
// DO NOT EDIT

use crate::Device;
use glib::translate::*;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "AtspiDeviceX11")]
    pub struct DeviceX11(Object<ffi::AtspiDeviceX11, ffi::AtspiDeviceX11Class>) @extends Device;

    match fn {
        type_ => || ffi::atspi_device_x11_get_type(),
    }
}

impl DeviceX11 {
    #[doc(alias = "atspi_device_x11_new")]
    pub fn new() -> DeviceX11 {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::atspi_device_x11_new())
        }
    }
}

impl Default for DeviceX11 {
    fn default() -> Self {
        Self::new()
    }
}

pub const NONE_DEVICE_X11: Option<&DeviceX11> = None;

impl fmt::Display for DeviceX11 {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("DeviceX11")
    }
}
